import { testGenerateShield, testGenerateShieldsForFiles } from './generateShield.js'
import { Project } from 'ts-morph'
import { expect, describe, it } from 'vitest'

// Hook ts-morph's Program.compilerObject getter once for the whole
// file. When `seenPrograms` is non-null, every getter access records
// the underlying ts.Program reference; this lets us count distinct
// Program rebuilds during a measured operation. When null, the hook
// is a transparent passthrough so other tests are unaffected.
let seenPrograms: Set<unknown> | null = null
{
  const tmp = new Project({ compilerOptions: { strict: true, skipLibCheck: true } })
  const proto = Object.getPrototypeOf(tmp.getProgram())
  const desc = Object.getOwnPropertyDescriptor(proto, 'compilerObject')
  if (!desc?.get) throw new Error('expected ts-morph Program.compilerObject getter')
  const origGet = desc.get
  Object.defineProperty(proto, 'compilerObject', {
    ...desc,
    get(this: unknown) {
      const value = origGet.call(this)
      seenPrograms?.add(value)
      return value
    },
  })
}

describe('generateShield', () => {
  it('generateShield, one telefunction', async () => {
    const src = `export function doSomething(arg: string) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, two telefunctions', async () => {
    const src = `export function doSomething(arg: string) {

}

export function doSomethingElse(arg: string | number, arg2: { val?: number }) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      __telefunc_shield(doSomethingElse, [__telefunc_t.or(__telefunc_t.number, __telefunc_t.string), { val: __telefunc_t.optional(__telefunc_t.number) }], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, real use case', async () => {
    const src = `import { __decorateTelefunction } from "telefunc";export function onFoo(bar: string, baz: Attending) {
        console.log({ bar });
}

export enum Attending {
        MAYBE = 'MAYBE',
        ATTENDING = 'ATTENDING',
        NOT_ATTENDING = 'NOT_ATTENDING',
        UNKNOWN = 'UNKNOWN'
}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onFoo, [__telefunc_t.string, __telefunc_t.or(__telefunc_t.const('UNKNOWN'), __telefunc_t.const('NOT_ATTENDING'), __telefunc_t.const('ATTENDING'), __telefunc_t.const('MAYBE'))], { __autoGenerated: true });
      "
    `)
  })

  it('generateShieldsForFiles, multi-file batch with non-colliding fileTags', async () => {
    const shields = await testGenerateShieldsForFiles([
      {
        fileName: 'foo.telefunc.ts',
        code: `export function foo(arg: string) {}`,
      },
      {
        fileName: 'bar.telefunc.ts',
        code: `export function bar(arg: number, opts: { x?: boolean }) {}`,
      },
      {
        fileName: 'baz.telefunc.ts',
        // Same export name as `foo` — verifies fileTag prevents alias collisions.
        code: `export function foo(arg: { val: string | number }) {}`,
      },
    ])
    expect(shields.get('foo.telefunc.ts')).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(foo, [__telefunc_t.string], { __autoGenerated: true });
      "
    `)
    expect(shields.get('bar.telefunc.ts')).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(bar, [__telefunc_t.number, { x: __telefunc_t.optional(__telefunc_t.boolean) }], { __autoGenerated: true });
      "
    `)
    expect(shields.get('baz.telefunc.ts')).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(foo, [{ val: __telefunc_t.or(__telefunc_t.number, __telefunc_t.string) }], { __autoGenerated: true });
      "
    `)
  })

  it('generateShieldsForFiles, Program rebuilds do not scale with file count', async () => {
    const measure = async (n: number, prefix: string) => {
      seenPrograms = new Set()
      await testGenerateShieldsForFiles(
        Array.from({ length: n }, (_, i) => ({
          fileName: `${prefix}-${i}.telefunc.ts`,
          code: `export function fn${i}(arg: string, opt: { x?: number }) {}`,
        })),
      )
      const count = seenPrograms!.size
      seenPrograms = null
      return count
    }
    const small = await measure(2, 'small')
    const large = await measure(8, 'large')
    // Working impl: one TypeChecker handles every file in the read
    // loop, so distinct Program count is constant (1) regardless of N.
    // A regression to per-file generation would mutate the AST during
    // reads, invalidating the Program once per file — count would
    // scale with N (verified by injecting an addTypeAlias mid-loop:
    // small=3, large=9 with N=2 / N=8). `large <= small` cleanly
    // distinguishes both regimes.
    expect(large).toBeLessThanOrEqual(small)
  })

  it('edge cases', async () => {
    const code = `export { someFunc as onLoad }

const someFunc = async ({ name }: { name: string }) => {
  const message = 'Welcome ' + name
  return { message }
}`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(someFunc, [{ name: __telefunc_t.string }], { __autoGenerated: true });
      "
    `)
  })
})
