import { testGenerateShield } from './generateShield.js'
import { expect, describe, it } from 'vitest'

describe('generateShield', () => {
  it('generateShield, one telefunction', async () => {
    const src = `export function doSomething(arg: string) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, two telefunctions', async () => {
    const src = `export function doSomething(arg: string) {

}

export function doSomethingElse(arg: string | number, arg2: { val?: number }) {

}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(doSomething, [__telefunc_t.string], { __autoGenerated: true });
      __telefunc_shield(doSomethingElse, [__telefunc_t.or(__telefunc_t.number, __telefunc_t.string), { val: __telefunc_t.optional(__telefunc_t.number) }], { __autoGenerated: true });
      "
    `)
  })

  it('generateShield, real use case', async () => {
    const src = `import { __decorateTelefunction } from "telefunc";export function onFoo(bar: string, baz: Attending) {
        console.log({ bar });
}

export enum Attending {
        MAYBE = 'MAYBE',
        ATTENDING = 'ATTENDING',
        NOT_ATTENDING = 'NOT_ATTENDING',
        UNKNOWN = 'UNKNOWN'
}`
    const shieldedSrc = await testGenerateShield(src)
    expect(shieldedSrc).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onFoo, [__telefunc_t.string, __telefunc_t.or(__telefunc_t.const('UNKNOWN'), __telefunc_t.const('NOT_ATTENDING'), __telefunc_t.const('ATTENDING'), __telefunc_t.const('MAYBE'))], { __autoGenerated: true });
      "
    `)
  })

  it('edge cases', async () => {
    const code = `export { someFunc as onLoad }

const someFunc = async ({ name }: { name: string }) => {
  const message = 'Welcome ' + name
  return { message }
}`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(someFunc, [{ name: __telefunc_t.string }], { __autoGenerated: true });
      "
    `)
  })

  it('callable arg whose return is void/Promise<void> asserts `undefined` at runtime', async () => {
    // A callback typed `() => Promise<void>` must actually return `undefined` at runtime —
    // otherwise `if (await cb()) …` branches unpredictably on client-returned garbage. The
    // sub-shield therefore emits `[const(undefined)]` for void returns, not nothing.
    const code = `
export function onWithVoidCallback(cb: (percent: number) => Promise<void>) {}
export function onWithTypedCallback(cb: (n: number) => Promise<number>) {}
`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onWithVoidCallback, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onWithVoidCallback, { "0": { return: [__telefunc_t.const(undefined)] } });
      __telefunc_shield(onWithTypedCallback, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onWithTypedCallback, { "0": { return: [__telefunc_t.number] } });
      "
    `)
  })

  it('shielded-marker entries: every type (void, never, unknown) yields a concrete runtime shield', async () => {
    const code = `
import type { TELEFUNC_SHIELDS } from './shield-key.js'
declare global {
  namespace Telefunc {
    interface ShieldTypeMap {}
  }
}
type Payload<T, U> = {
  readonly [TELEFUNC_SHIELDS]: {
    data: T
    ack: U
    empty: never
  }
}
export function onMixed(arg: Payload<string, void>) {}
`
    // data = string → __telefunc_t.string
    // ack  = void   → __telefunc_t.const(undefined)  (accepts only undefined)
    // empty = never → __telefunc_t.never             (rejects every value)
    // No entry is silently skipped — every TS type position gets a concrete runtime validator.
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onMixed, [{  }], { __autoGenerated: true });
      __applyArgumentShields(onMixed, { "0": { data: [__telefunc_t.string], ack: [__telefunc_t.const(undefined)], empty: [__telefunc_t.never] } });
      "
    `)
  })

  it('ExtensionType picks most-specific when multiple ShieldTypeMap entries match', async () => {
    const code = `
declare global {
  namespace Telefunc {
    interface ShieldTypeMap {
      animal: { __brand_animal: true }
      dog: { __brand_animal: true; __brand_dog: true }
    }
  }
}
export function onAnimalArg(a: { __brand_animal: true }) {}
export function onDogArg(d: { __brand_animal: true; __brand_dog: true }) {}
`
    const codeShield = await testGenerateShield(code)
    expect(codeShield).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onAnimalArg, [__telefunc_t.animal], { __autoGenerated: true });
      __telefunc_shield(onDogArg, [__telefunc_t.dog], { __autoGenerated: true });
      "
    `)
  })
})

// ===========================================================================
// Characterization tests — black-box snapshots of `testGenerateShield()`.
//
// These pin the *exact* generated code for every code path of the shield
// generator (every `walkSites` branch × arg/return side, every leaf type,
// grouping/path-key shapes, and the failure path). They intentionally test
// only observable output (source in → shield code out), so they survive an
// internal refactor and flag any behavioral drift precisely. Where current
// behavior is subtle or surprising, a comment calls it out.
// ===========================================================================

describe('main shield — scalar & leaf types', () => {
  it('primitives & built-in special types (boolean, Date, File, Blob, ReadableStream, any, unknown)', async () => {
    const code = `export function onLeaf(
  a: boolean, b: Date, c: File, d: Blob, e: ReadableStream, f: any, g: unknown,
) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onLeaf, [__telefunc_t.boolean, __telefunc_t.date, __telefunc_t.file, __telefunc_t.blob, __telefunc_t.readableStream, __telefunc_t.any, __telefunc_t.any], { __autoGenerated: true });
      "
    `)
  })

  it('union → or()', async () => {
    const code = `export function onUnion(a: string | number) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onUnion, [__telefunc_t.or(__telefunc_t.number, __telefunc_t.string)], { __autoGenerated: true });
      "
    `)
  })

  it('nullable → nullable()', async () => {
    const code = `export function onNullable(a: string | null) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onNullable, [__telefunc_t.nullable(__telefunc_t.string)], { __autoGenerated: true });
      "
    `)
  })

  it('optional parameter → optional()', async () => {
    const code = `export function onOptional(a?: number) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onOptional, [__telefunc_t.optional(__telefunc_t.number)], { __autoGenerated: true });
      "
    `)
  })

  it('literal types → const()', async () => {
    const code = `export function onLiteral(a: 'x' | 'y', b: 42, c: true) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onLiteral, [__telefunc_t.or(__telefunc_t.const('y'), __telefunc_t.const('x')), __telefunc_t.const(42), __telefunc_t.const(true)], { __autoGenerated: true });
      "
    `)
  })

  it('void top-level arg → optional(const(undefined))', async () => {
    const code = `export function onVoidArg(a: void) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onVoidArg, [__telefunc_t.optional(__telefunc_t.const(undefined))], { __autoGenerated: true });
      "
    `)
  })

  it('array arg → array() and is terminal (no sub-shield walked into the element callable)', async () => {
    const code = `export function onArray(cbs: Array<() => void>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onArray, [__telefunc_t.array(__telefunc_t.function)], { __autoGenerated: true });
      "
    `)
  })

  it('class instance arg is expanded structurally for the main shield (and not recursed for sub-shields)', async () => {
    const code = `class Foo { x = 1 }
export function onClassArg(foo: Foo) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onClassArg, [{ x: __telefunc_t.number }], { __autoGenerated: true });
      "
    `)
  })
})

describe('main shield — failure cases (no shield line emitted)', () => {
  // When the type doesn't resolve to a string literal, `mainShield === undefined`:
  // the record is marked `failed` and NO `__telefunc_shield(...)` line is emitted.
  // (The failure is otherwise surfaced via logResult() warnings, which the test
  // harness doesn't invoke — so here we observe it as the absence of a shield line.)
  it('`never` top-level arg fails (only the header is emitted)', async () => {
    const code = `export function onNeverArg(a: never) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      "
    `)
  })

  it('`undefined` top-level arg fails (only the header is emitted)', async () => {
    const code = `export function onUndefinedArg(a: undefined) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      "
    `)
  })
})

describe('argument sub-shields — callbacks flowing into a telefunction', () => {
  it('callback returning a typed value (sync and Promise resolve identically via Awaited)', async () => {
    const code = `export function onSyncCb(cb: () => number) {}
export function onAsyncCb(cb: () => Promise<number>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onSyncCb, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onSyncCb, { "0": { return: [__telefunc_t.number] } });
      __telefunc_shield(onAsyncCb, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onAsyncCb, { "0": { return: [__telefunc_t.number] } });
      "
    `)
  })

  it('callback parameters are ignored on the arg side — only its return type is shielded', async () => {
    const code = `export function onCbParams(cb: (a: string, b: number) => Promise<boolean>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onCbParams, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onCbParams, { "0": { return: [__telefunc_t.boolean] } });
      "
    `)
  })

  it('callback returning an object containing another callable — return shielded flat, no deep recurse', async () => {
    const code = `export function onCbNestedReturn(cb: () => Promise<{ inner: () => void }>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onCbNestedReturn, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onCbNestedReturn, { "0": { return: [{ inner: __telefunc_t.function }] } });
      "
    `)
  })

  it('multiple callback args → distinct path keys "0" and "1"', async () => {
    const code = `export function onMultiCb(first: (a: number) => void, second: (b: string) => Promise<number>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onMultiCb, [__telefunc_t.function, __telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onMultiCb, { "0": { return: [__telefunc_t.const(undefined)] }, "1": { return: [__telefunc_t.number] } });
      "
    `)
  })

  it('callback nested in an ANONYMOUS object arg → compound path key "0.onProgress"', async () => {
    const code = `export function onAnonOpts(opts: { onProgress: (n: number) => Promise<void> }) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onAnonOpts, [{ onProgress: __telefunc_t.function }], { __autoGenerated: true });
      __applyArgumentShields(onAnonOpts, { "0.onProgress": { return: [__telefunc_t.const(undefined)] } });
      "
    `)
  })

  it('callback nested in a TUPLE arg → compound path key "0.0"', async () => {
    const code = `export function onTupleArg(pair: [(n: number) => void, string]) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onTupleArg, [__telefunc_t.tuple(__telefunc_t.function, __telefunc_t.string)], { __autoGenerated: true });
      __applyArgumentShields(onTupleArg, { "0.0": { return: [__telefunc_t.const(undefined)] } });
      "
    `)
  })

  it('callback inside a NAMED interface is NOT recursed → no sub-shield (only anonymous objects descend)', async () => {
    const code = `interface NamedOpts { onProgress: (n: number) => void }
export function onNamedOpts(opts: NamedOpts) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onNamedOpts, [{ onProgress: __telefunc_t.function }], { __autoGenerated: true });
      "
    `)
  })
})

describe('return sub-shields — values flowing out of a telefunction', () => {
  it('telefunction returning a callable directly → key "" with the callback parameter shields as `args`', async () => {
    const code = `export function onReturnsCb(): (a: string, b: number) => Promise<boolean> { return async () => true }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onReturnsCb, [], { __autoGenerated: true });
      __applyReturnShields(onReturnsCb, { "": { args: [__telefunc_t.string, __telefunc_t.number] } });
      "
    `)
  })

  it('return object containing a callable → key "cb"', async () => {
    const code = `export function onReturnsObj(): { cb: () => Promise<number> } { return { cb: async () => 1 } }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onReturnsObj, [], { __autoGenerated: true });
      __applyReturnShields(onReturnsObj, { "cb": { args: [] } });
      "
    `)
  })

  it('return tuple containing a callable → key "0"', async () => {
    const code = `export function onReturnsTuple(): [() => Promise<string>, number] { return [async () => 'x', 1] }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onReturnsTuple, [], { __autoGenerated: true });
      __applyReturnShields(onReturnsTuple, { "0": { args: [] } });
      "
    `)
  })

  it('async telefunction return is unwrapped via Awaited before walking', async () => {
    const code = `export async function onAsyncReturn(): Promise<{ cb: () => Promise<string> }> { return { cb: async () => 'x' } }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onAsyncReturn, [], { __autoGenerated: true });
      __applyReturnShields(onAsyncReturn, { "cb": { args: [] } });
      "
    `)
  })

  it('void return emits no return sub-shield', async () => {
    const code = `export function onVoidReturn(): void {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onVoidReturn, [], { __autoGenerated: true });
      "
    `)
  })
})

describe('TELEFUNC_SHIELDS marker', () => {
  it('marker on the RETURN position with a generic parameter', async () => {
    const code = `import type { TELEFUNC_SHIELDS } from './shield-key.js'
type Box<T> = { readonly [TELEFUNC_SHIELDS]: { value: T } }
export function onBoxReturn(): Box<number> { return {} as any }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onBoxReturn, [], { __autoGenerated: true });
      __applyReturnShields(onBoxReturn, { "": { value: [__telefunc_t.number] } });
      "
    `)
  })

  it('marker intersected onto a room-shaped interface, returned as a Promise — the Room publish shield', async () => {
    // Faithful to `Room<M, P, Pub> = { … } & RoomShield<Pub>` (wire-protocol/room/types.ts): the marker
    // is intersected onto an interface carrying real members (`id`, `publish`), and the telefunction
    // returns it as a `Promise`. The transform must find the marker through both, emit *only* its `data`
    // slot (never the sibling members), and descend `Pub` into a runtime object shield — the mechanism
    // that makes `Room<…, ChatMsg>` validate every client `publish()` with no shield to hand-write.
    const code = `import type { TELEFUNC_SHIELDS } from './shield-key.js'
type RoomShield<Pub> = { readonly [TELEFUNC_SHIELDS]: { data: Pub } }
type Room<Pub> = {
  id: string
  publish(data: Pub): Promise<void>
} & RoomShield<Pub>
type ChatMsg = { kind: 'chat'; text: string }
export async function onGetTypedRoom(): Promise<Room<ChatMsg>> { return {} as any }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onGetTypedRoom, [], { __autoGenerated: true });
      __applyReturnShields(onGetTypedRoom, { "": { data: [{ text: __telefunc_t.string, kind: __telefunc_t.const('chat') }] } });
      "
    `)
  })

  it('marker with multiple entries → grouped under one path key', async () => {
    const code = `import type { TELEFUNC_SHIELDS } from './shield-key.js'
type Multi = { readonly [TELEFUNC_SHIELDS]: { a: string; b: number; c: boolean } }
export function onMultiMarker(arg: Multi) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onMultiMarker, [{  }], { __autoGenerated: true });
      __applyArgumentShields(onMultiMarker, { "0": { a: [__telefunc_t.string], b: [__telefunc_t.number], c: [__telefunc_t.boolean] } });
      "
    `)
  })
})

describe('ShieldTypeMap extensions', () => {
  // NOTE: `getProject()` caches one ts-morph Project per tsconfig (here the no-tsconfig
  // one) for the whole spec run, and virtual telefunc files are never removed from it —
  // so every `declare global { … ShieldTypeMap … }` accumulates across tests. Each test
  // below therefore uses a UNIQUE brand so its arg matches only its own key, keeping the
  // snapshots order-independent. Reuse a brand across tests and they'll cross-contaminate.
  it('basic single match → __telefunc_t.<key>', async () => {
    const code = `declare global {
  namespace Telefunc {
    interface ShieldTypeMap {
      widget: { __brand_widget: true }
    }
  }
}
export function onWidget(a: { __brand_widget: true }) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onWidget, [__telefunc_t.widget], { __autoGenerated: true });
      "
    `)
  })

  it('extension type resolves inside a callback-return sub-shield position', async () => {
    const code = `declare global {
  namespace Telefunc {
    interface ShieldTypeMap {
      gizmo: { __brand_gizmo: true }
    }
  }
}
export function onGizmoCb(cb: () => Promise<{ __brand_gizmo: true }>) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onGizmoCb, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onGizmoCb, { "0": { return: [__telefunc_t.gizmo] } });
      "
    `)
  })
})

describe('combinations & module-level output', () => {
  it('both argument and return sub-shields on the same telefunction', async () => {
    const code = `export function onBoth(cb: (n: number) => void): () => Promise<string> { return async () => 'x' }`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onBoth, [__telefunc_t.function], { __autoGenerated: true });
      __applyReturnShields(onBoth, { "": { args: [] } });
      __applyArgumentShields(onBoth, { "0": { return: [__telefunc_t.const(undefined)] } });
      "
    `)
  })

  it('mix of shielded fn, plain fn, and a non-function export (the const is skipped)', async () => {
    const code = `export const notAFn = 123
export function onPlain(a: string) {}
export function onWithCb(cb: () => void) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onPlain, [__telefunc_t.string], { __autoGenerated: true });
      __telefunc_shield(onWithCb, [__telefunc_t.function], { __autoGenerated: true });
      __applyArgumentShields(onWithCb, { "0": { return: [__telefunc_t.const(undefined)] } });
      "
    `)
  })

  it('default export is shielded', async () => {
    const code = `export default function onDefault(arg: string) {}`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      __telefunc_shield(onDefault, [__telefunc_t.string], { __autoGenerated: true });
      "
    `)
  })

  it('module with no function exports → only the header is emitted', async () => {
    const code = `export const x = 1
export type Y = string`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      "
    `)
  })

  it('empty module → only the header is emitted', async () => {
    const code = `const x = 1`
    expect(await testGenerateShield(code)).toMatchInlineSnapshot(`
      "import { shield as __telefunc_shield, __applyReturnShields, __applyArgumentShields } from "telefunc";
      const __telefunc_t = __telefunc_shield.type;
      "
    `)
  })
})
